//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJUTxiaomei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        public string BuildingsName { get; set; }
        public string OpenHours { get; set; }
        public string AddressDescription { get; set; }
        public string AddressImage { get; set; }
        public string Address3D { get; set; }
        public string Phone { get; set; }
    }
}
